#! /usr/bin/env zsh
setopt LIST_ROWS_FIRST

# share history
export HISTSIZE=1000
export SAVEHIST=1000
export HISTFILE="${HOME}/.zsh/.history"
setopt inc_append_history
setopt share_history
setopt auto_cd
