#! /usr/bin/env zsh

autoload -Uz compinit
autoload -U colors && colors
compinit

# Default Prompt
PROMPT="%B%(?..[%?] )%b%n%F{240}@%f%U%m%u>"
RPROMPT="%{$fg[green]%}%~%{$reset_color%}"

# zle: update VIMMODE on mode chagne
function zle-line-init zle-keymap-select {
    vimode="${${KEYMAP/vicmd/[n]}/(main|viins)/[i]}"
    PROMPT="${vimode} %B%(?..[%?] )%b%n%F{240}@%f%U%m%u>"
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
