#! /bin/sh
# aliases for all shells

# common
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias cdh='urxvt -cd $(pwd) &'
alias vim='nvim'
alias pj='pijul'

# admin
alias sys='systemctl'
alias ssys='sudo systemctl'

# dev
alias cwatch="cargo watch --clear"
alias nix-ipython='nix-shell --run ipython'
